### PR TITLE
feat: add import ordering rule (EXP-102)

### PR DESCRIPTION
**Pull request by AdamVig**
- [`eslint-plugin-import`](https://github.com/benmosher/eslint-plugin-import)
  - [`order` rule](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md)
  - [`no-self-import` rule](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-self-import.md)
  - [`newline-after-import` rule](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/newline-after-import.md)

### Before
```TypeScript
import {assert, AssertionError} from 'chai';
import sinon from 'sinon';
import {MfpUiElement} from '@sixriver/mfp-ui-element';
import {PowerState} from '@sixriver/mfp-ui-models';
import {State} from '@sixriver/mfp-ui-transport';
import {initialize} from './app';
import {MockPublisher} from '../transport/mock-publisher';
import {MockSubscriber} from '../transport/mock-subscriber';
// no newline after imports
```

### After
```TypeScript
import {MfpUiElement} from '@sixriver/mfp-ui-element';
import {PowerState} from '@sixriver/mfp-ui-models';
import {State} from '@sixriver/mfp-ui-transport';
import {assert, AssertionError} from 'chai';
import sinon from 'sinon';

import {MockPublisher} from '../transport/mock-publisher';
import {MockSubscriber} from '../transport/mock-subscriber';
import {initialize} from './app';
// newline between imports and other code

```

- feat: enforce new line after imports

- feat: prevent self-imports

- feat: add import ordering rule
  BREAKING CHANGE:
  Imports will now be validated and auto-fixed when possible. The import
  ordering rule is configured to:
  - group built-in and external imports (Node libraries, third-party dependencies)
  - group internal imports
  - separate the two groups with a blank line
  - alphabetize the imports in each group by import path

### CODE REVIEW

**Comment by Shockolate** [comment]
I'm glad that this is a thing now! I've personally ordered imports in each file I touch. 
Could you provide a before/after example?

**Comment by mgabeler-lee-6rs** [comment]
NB from Slack: I'm OK with taking this as-is, or with adding a "no importing from '.'" rule to it given the risk of import cycles that produces

**Comment by tonygaetani** [comment]
I would love a "no import from '.'" rule too

**Comment by AdamVig** [comment]
@tonygaetani Already implemented! See [`no-self-import`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-self-import.md).

**Comment by andrasq** [comment]
is the example actual code?  Aren't spaces banned between the `{` and the curly contents?

**Comment by AdamVig** [comment]
@andrasq Good catch! This is code from [`mfp-ui`](https://github.com/6RiverSystems/mfp-ui), which uses Prettier with our [`@6river/prettier-config`](https://github.com/6RiverSystems/prettier-config), which uses spaces around the curly braces.

I'll change the example to avoid confusion.

**Comment by mgabeler-lee-6rs** [comment]
FWIW, I'm of the opinion that we should start slowly rolling that prettier config out to the FS repos too for consistency

**Pull request merged**
