### PR TITLE
fix: don't allow assignment in conditionals - MFPLAT-326

### PR DESCRIPTION
**Pull request by asdo6rs**

### CODE REVIEW

**Comment by asdo6rs** [comment]
Not having this led to MFLAT-326 in mfp-core.  I think we should enforce this across all our code.  What do folks think?

**Comment by tonygaetani** [comment]
Makes sense to me, I think we should do it :+1: @townbully @mgabeler-lee-6rs @AdamVig any reason you can think of to not do this?

**Review by mgabeler-lee-6rs — APPROVED** [review]
strong +1 to this

**Comment by AdamVig** [comment]
Apparently the `automerge` is a bit overzealous :laughing: I'll fix that, but anyways, I agree and I'm glad you added this. :+1:

**Review by townbully — COMMENTED** [review]
👍

**Pull request merged**
